name: Auto Image Rebuild
on:
  schedule:
    - cron: "0 3 * * 1"
  workflow_dispatch:

jobs:
  build-latest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Regular Docker Image
        uses: docker/build-push-action@v5
        with:
          context: "${{ github.workspace }}"
          platforms: linux/amd64,linux/arm64
          push: true
          tags: junklabs/caddy-cloudflare-dynamicdns:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  build-alpine:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Alpine Docker Image
        uses: docker/build-push-action@v5
        with:
          context: "${{ github.workspace }}"
          platforms: linux/amd64,linux/arm64
          push: true
          tags: junklabs/caddy-cloudflare-dynamicdns:alpine
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: "Dockerfile.alpine"
